[general]
live_config_reload = true

import = [
  "~/.config/alacritty/onedark.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
# family = "JetBrainsMono Nerd Font"
# style = "Bold"
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold]
# family = "JetBrainsMono Nerd Font"
# style = "Bold"
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "JetBrainsMono Nerd Font"
# style = "Bold Italic"
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "JetBrainsMono Nerd Font"
# style = "Bold Italic"
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = -1
y = -1

[window]
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 200
lines = 50

[window.padding]
x = 25
y = 25

# [terminal.shell]
# program = "tmux"

[keyboard]
bindings = [
    { key = "Escape", mods = "Control", action = "ToggleViMode" },
]
